name: Build and Deploy Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_PACKAGES_FEED_URL: https://nuget.pkg.github.com/mephystus/index.json
  BUILD_CONFIGURATION: 'Release'    
  DOTNET_VERSION: '6.0.x' 
  CONTAINER_REGISTRY: 'acrrbichodev01.azurecr.io'
  CONTAINER_REGISTRY_USERNAME: 'acrrbichodev01'
  CONTAINER_REGISTRY_REPOSITORY: 'customer.api'
  AZURE_WEBAPP_NAME: 'rbicho-customer-api'
 
defaults:
  run:
    working-directory: ./src
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        source-url: ${{ env.GITHUB_PACKAGES_FEED_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} -p:GeneratePackageOnBuild=false
         
    - name: Create package(s)
      run: dotnet pack -c ${{ env.BUILD_CONFIGURATION }} -p:PackageVersion=1.1.${GITHUB_RUN_NUMBER}
            
    - name: Publish package(s)
      run: dotnet nuget push --source ${{ env.GITHUB_ARTIFACTS_FEED_URL }} --api-key ${{ secrets.GITHUB_TOKEN }} **/Customer.Api.Client/bin/Release/*.nupkg

    - name: Publish API
      run: dotnet publish 'Customer.Api/Customer.Api.csproj' --no-build --configuration '${{ env.BUILD_CONFIGURATION }}' --output './../publish'
        
    - name: Login to Azure Container Registry 
      uses: azure/docker-login@v1
      with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ env.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      
    - name: Push to Azure Container Registry
      run: |
          docker build -f docker/Dockerfile . -t ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REGISTRY_REPOSITORY }}:${{ github.sha }}
          docker push ${{env.CONTAINER_REGISTRY}}/${{ env.CONTAINER_REGISTRY_REPOSITORY }}:${{ github.sha }}
      working-directory: ./
    
    - name: 'Deploy to Azure Web App for Container'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_REGISTRY_REPOSITORY }}:${{ github.sha }}
